name: CI for Linux

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          grep -vE '^\s*#|^\s*$' .devcontainer/apt-packages.txt | xargs sudo apt-get install -y

      - name: Run tests
        run: |
          python3 --version
          python3 -m unittest discover -s src/linux -p "test_*.py"

  check-finished:
    name: Check finished CI
    runs-on: ubuntu-latest
    if: always()
    needs:
      - test
    permissions:
      actions: read

    steps:
      - name: Check build failure
        run: |
          echo "Build status: ${{ needs.test.result }}"
          if [ "${{ needs.test.result }}" != "success" ]; then
            echo "Build failed"
            exit 1
          fi
